export const MENUS = [
  {
    name: "Dashboard",
    path: "/dashboard",
  },
  {
    name: "Market",
    path: "/market",
  },
];

export const DEFAULT_CURRENCY = "usd";

export const FIATS_MAP = {
  usd: { name: "United States Dollar", sign: "$", symbol: "USD" },
  aud: { name: "Australian Dollar", sign: "$", symbol: "AUD" },
  brl: { name: "Brazilian Real", sign: "R$", symbol: "BRL" },
  cad: { name: "Canadian Dollar", sign: "$", symbol: "CAD" },
  chf: { name: "Swiss Franc", sign: "Fr", symbol: "CHF" },
  clp: { name: "Chilean Peso", sign: "$", symbol: "CLP" },
  cny: { name: "Chinese Yuan", sign: "¥", symbol: "CNY" },
  czk: { name: "Czech Koruna", sign: "Kč", symbol: "CZK" },
  dkk: { name: "Danish Krone", sign: "kr", symbol: "DKK" },
  eur: { name: "Euro", sign: "€", symbol: "EUR" },
  gbp: { name: "Pound Sterling", sign: "£", symbol: "GBP" },
  hkd: { name: "Hong Kong Dollar", sign: "$", symbol: "HKD" },
  huf: { name: "Hungarian Forint", sign: "Ft", symbol: "HUF" },
  idr: { name: "Indonesian Rupiah", sign: "Rp", symbol: "IDR" },
  ils: { name: "Israeli New Shekel", sign: "₪", symbol: "ILS" },
  inr: { name: "Indian Rupee", sign: "₹", symbol: "INR" },
  jpy: { name: "Japanese Yen", sign: "¥", symbol: "JPY" },
  krw: { name: "South Korean Won", sign: "₩", symbol: "KRW" },
  mxn: { name: "Mexican Peso", sign: "$", symbol: "MXN" },
  myr: { name: "Malaysian Ringgit", sign: "RM", symbol: "MYR" },
  nok: { name: "Norwegian Krone", sign: "kr", symbol: "NOK" },
  nzd: { name: "New Zealand Dollar", sign: "$", symbol: "NZD" },
  php: { name: "Philippine Peso", sign: "₱", symbol: "PHP" },
  pkr: { name: "Pakistani Rupee", sign: "₨", symbol: "PKR" },
  pln: { name: "Polish Złoty", sign: "zł", symbol: "PLN" },
  rub: { name: "Russian Ruble", sign: "₽", symbol: "RUB" },
  sek: { name: "Swedish Krona", sign: "kr", symbol: "SEK" },
  sgd: { name: "Singapore Dollar", sign: "S$", symbol: "SGD" },
  thb: { name: "Thai Baht", sign: "฿", symbol: "THB" },
  try: { name: "Turkish Lira", sign: "₺", symbol: "TRY" },
  twd: { name: "New Taiwan Dollar", sign: "NT$", symbol: "TWD" },
  zar: { name: "South African Rand", sign: "R", symbol: "ZAR" },
  aed: { name: "United Arab Emirates Dirham", sign: "د.إ", symbol: "AED" },
  ngn: { name: "Nigerian Naira", sign: "₦", symbol: "NGN" },
  ars: { name: "Argentine Peso", sign: "$", symbol: "ARS" },
  vnd: { name: "Vietnamese Dong", sign: "₫", symbol: "VND" },
  uah: { name: "Ukrainian Hryvnia", sign: "₴", symbol: "UAH" },
  bdt: { name: "Bangladeshi Taka", sign: "৳", symbol: "BDT" },
  sar: { name: "Saudi Riyal", sign: "ر.س", symbol: "SAR" },
};

export const FIATS_ARRAY = [
  { label: "usd", value: "usd" },
  { label: "aud", value: "aud" },
  { label: "brl", value: "brl" },
  { label: "cad", value: "cad" },
  { label: "chf", value: "chf" },
  { label: "clp", value: "clp" },
  { label: "cny", value: "cny" },
  { label: "czk", value: "czk" },
  { label: "dkk", value: "dkk" },
  { label: "eur", value: "eur" },
  { label: "gbp", value: "gbp" },
  { label: "hkd", value: "hkd" },
  { label: "huf", value: "huf" },
  { label: "idr", value: "idr" },
  { label: "ils", value: "ils" },
  { label: "inr", value: "inr" },
  { label: "jpy", value: "jpy" },
  { label: "krw", value: "krw" },
  { label: "mxn", value: "mxn" },
  { label: "myr", value: "myr" },
  { label: "nok", value: "nok" },
  { label: "nzd", value: "nzd" },
  { label: "php", value: "php" },
  { label: "pkr", value: "pkr" },
  { label: "pln", value: "pln" },
  { label: "rub", value: "rub" },
  { label: "sek", value: "sek" },
  { label: "sgd", value: "sgd" },
  { label: "thb", value: "thb" },
  { label: "try", value: "try" },
  { label: "twd", value: "twd" },
  { label: "zar", value: "zar" },
  { label: "aed", value: "aed" },
  { label: "ngn", value: "ngn" },
  { label: "ars", value: "ars" },
  { label: "vnd", value: "vnd" },
  { label: "uah", value: "uah" },
  { label: "bdt", value: "bdt" },
  { label: "sar", value: "sar" },
];

export const REFRESH_TOKEN_MAX_AGE = 7 * 24 * 60 * 60 * 1000;
export const ACCESS_TOKEN_MAX_AGE = 15 * 60 * 1000;
export const TABS = ["transactions", "overview"];
export const OVERVIEW_OPTIONS = [
  {
    label: "Weekly",
    value: "7",
  },
  {
    label: "Monthly",
    value: "30",
  },
];
