export const MENUS = [
  {
    name: "Dashboard",
    path: "/dashboard",
  },
  {
    name: "Market",
    path: "/market",
  },
];

export const FIATS = [
  { id: 2781, name: "United States Dollar", sign: "$", symbol: "USD" },
  { id: 2782, name: "Australian Dollar", sign: "$", symbol: "AUD" },
  { id: 2783, name: "Brazilian Real", sign: "R$", symbol: "BRL" },
  { id: 2784, name: "Canadian Dollar", sign: "$", symbol: "CAD" },
  { id: 2785, name: "Swiss Franc", sign: "Fr", symbol: "CHF" },
  { id: 2786, name: "Chilean Peso", sign: "$", symbol: "CLP" },
  { id: 2787, name: "Chinese Yuan", sign: "¥", symbol: "CNY" },
  { id: 2788, name: "Czech Koruna", sign: "Kč", symbol: "CZK" },
  { id: 2789, name: "Danish Krone", sign: "kr", symbol: "DKK" },
  { id: 2790, name: "Euro", sign: "€", symbol: "EUR" },
  { id: 2791, name: "Pound Sterling", sign: "£", symbol: "GBP" },
  { id: 2792, name: "Hong Kong Dollar", sign: "$", symbol: "HKD" },
  { id: 2793, name: "Hungarian Forint", sign: "Ft", symbol: "HUF" },
  { id: 2794, name: "Indonesian Rupiah", sign: "Rp", symbol: "IDR" },
  { id: 2795, name: "Israeli New Shekel", sign: "₪", symbol: "ILS" },
  { id: 2796, name: "Indian Rupee", sign: "₹", symbol: "INR" },
  { id: 2797, name: "Japanese Yen", sign: "¥", symbol: "JPY" },
  { id: 2798, name: "South Korean Won", sign: "₩", symbol: "KRW" },
  { id: 2799, name: "Mexican Peso", sign: "$", symbol: "MXN" },
  { id: 2800, name: "Malaysian Ringgit", sign: "RM", symbol: "MYR" },
  { id: 2801, name: "Norwegian Krone", sign: "kr", symbol: "NOK" },
  { id: 2802, name: "New Zealand Dollar", sign: "$", symbol: "NZD" },
  { id: 2803, name: "Philippine Peso", sign: "₱", symbol: "PHP" },
  { id: 2804, name: "Pakistani Rupee", sign: "₨", symbol: "PKR" },
  { id: 2805, name: "Polish Złoty", sign: "zł", symbol: "PLN" },
  { id: 2806, name: "Russian Ruble", sign: "₽", symbol: "RUB" },
  { id: 2807, name: "Swedish Krona", sign: "kr", symbol: "SEK" },
  { id: 2808, name: "Singapore Dollar", sign: "S$", symbol: "SGD" },
  { id: 2809, name: "Thai Baht", sign: "฿", symbol: "THB" },
  { id: 2810, name: "Turkish Lira", sign: "₺", symbol: "TRY" },
  { id: 2811, name: "New Taiwan Dollar", sign: "NT$", symbol: "TWD" },
  { id: 2812, name: "South African Rand", sign: "R", symbol: "ZAR" },
  {
    id: 2813,
    name: "United Arab Emirates Dirham",
    sign: "د.إ",
    symbol: "AED",
  },
  { id: 2819, name: "Nigerian Naira", sign: "₦", symbol: "NGN" },
  { id: 2821, name: "Argentine Peso", sign: "$", symbol: "ARS" },
  { id: 2823, name: "Vietnamese Dong", sign: "₫", symbol: "VND" },
  { id: 2824, name: "Ukrainian Hryvnia", sign: "₴", symbol: "UAH" },
  { id: 3530, name: "Bangladeshi Taka", sign: "৳", symbol: "BDT" },
  { id: 3566, name: "Saudi Riyal", sign: "ر.س", symbol: "SAR" },
];
